/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristiano
 */
public class Jiemprestimo extends javax.swing.JInternalFrame {
private int valor;
  
    
    
    public Jiemprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtcod2 = new javax.swing.JTextField();
        Jtnomecliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Janela2 = new javax.swing.JTextField();
        Jtqtdadeparcelas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jtdataprimeiraparcela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtb2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jbnovo = new javax.swing.JButton();
        Jbeditar = new javax.swing.JButton();
        Jbsalvar = new javax.swing.JButton();
        Jbsair = new javax.swing.JButton();
        jbapagar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Emprestimo");
        setName(""); // NOI18N

        jtcod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcod2ActionPerformed(evt);
            }
        });

        Jtnomecliente.setEnabled(false);
        Jtnomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtnomeclienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod");

        jLabel2.setText("Nome Cliente");

        Janela2.setEnabled(false);
        Janela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Janela2ActionPerformed(evt);
            }
        });

        Jtqtdadeparcelas.setEnabled(false);
        Jtqtdadeparcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtqtdadeparcelasActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Emprestimo ");

        jLabel4.setText("Quantidade de Parcelas ");

        jLabel5.setText("Data da Primeira Parcela");

        Jtdataprimeiraparcela.setEnabled(false);

        Jtb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome Cliente", "Valor Empretimo", "Quantidade Parcelas", "Data Parcela 1"
            }
        ));
        jScrollPane1.setViewportView(Jtb2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Solicitação de Empréstimo");

        jbnovo.setText("Novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });

        Jbeditar.setText("Editar");
        Jbeditar.setEnabled(false);

        Jbsalvar.setText("Salvar");
        Jbsalvar.setEnabled(false);
        Jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsalvarActionPerformed(evt);
            }
        });

        Jbsair.setText("Sair");

        jbapagar.setText("Apagar");
        jbapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbapagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnovo)
                        .addGap(18, 18, 18)
                        .addComponent(Jbeditar)
                        .addGap(18, 18, 18)
                        .addComponent(Jbsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(Jbsair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbapagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(Janela2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(Jtqtdadeparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jtdataprimeiraparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtcod2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(Jtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Janela2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtqtdadeparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtdataprimeiraparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnovo)
                    .addComponent(Jbeditar)
                    .addComponent(Jbsalvar)
                    .addComponent(Jbsair)
                    .addComponent(jbapagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jLabel6.getAccessibleContext().setAccessibleName("Solicitação de Emprestimo");

        setBounds(0, 0, 571, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void JtnomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtnomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtnomeclienteActionPerformed

    private void JtqtdadeparcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtqtdadeparcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtqtdadeparcelasActionPerformed

    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed

        Jtnomecliente.setEnabled(true);
        Janela2.setEnabled(true);
        Jtqtdadeparcelas.setEnabled(true);
        Jtdataprimeiraparcela.setEnabled(true);
        
        
        Jbeditar.setEnabled(true);
        Jbsalvar.setEnabled(true);
        
        


    }//GEN-LAST:event_jbnovoActionPerformed

    private void jbapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbapagarActionPerformed

        ((DefaultTableModel) Jtb2.getModel()).removeRow(Jtb2.getSelectedRow());

    }//GEN-LAST:event_jbapagarActionPerformed

    private void jtcod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcod2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcod2ActionPerformed

    private void JbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsalvarActionPerformed
        String cod = jtcod2.getText().trim();
        String nomecliente = Jtnomecliente.getText().trim();
        String valoremprestimo = Janela2.getText().trim();
        String qtdadeparcelas = Jtqtdadeparcelas.getText().trim();
        String dataprimeiraparcela = Jtdataprimeiraparcela.getText().trim();
        

        DefaultTableModel val = (DefaultTableModel)Jtb2.getModel();
        val.addRow(new String[] {cod,nomecliente,valoremprestimo,qtdadeparcelas,dataprimeiraparcela});

        
        
        
        jtcod2.setText("");
        Jtnomecliente.setText("");
        Janela2.setText("");
        Jtqtdadeparcelas.setText("");
        Jtdataprimeiraparcela.setText("");
       
        
      

        Jtnomecliente.requestFocus();
        
        
        
        
    }//GEN-LAST:event_JbsalvarActionPerformed

    private void Janela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Janela2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Janela2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Janela2;
    private javax.swing.JButton Jbeditar;
    private javax.swing.JButton Jbsair;
    private javax.swing.JButton Jbsalvar;
    private javax.swing.JTable Jtb2;
    private javax.swing.JTextField Jtdataprimeiraparcela;
    private javax.swing.JTextField Jtnomecliente;
    private javax.swing.JTextField Jtqtdadeparcelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbapagar;
    private javax.swing.JButton jbnovo;
    private javax.swing.JTextField jtcod2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the valor
     */
    
}
