/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


//import conexao.DBConexion;
import javax.swing.table.DefaultTableModel;
import classes.cliente;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
        
/**
 *
 * @author Cristiano
 */
public class Jifcadastro extends javax.swing.JInternalFrame {


   
   
  
   
   
           
           
    public Jifcadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Jtnome = new javax.swing.JTextField();
        Jtend = new javax.swing.JTextField();
        Jtcpf = new javax.swing.JTextField();
        jbnovo = new javax.swing.JButton();
        jbexcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtb1 = new javax.swing.JTable();
        Jtcod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jtrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jtrenda = new javax.swing.JTextField();
        Jtsenha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Jtemail = new javax.swing.JTextField();
        Jbeditar = new javax.swing.JButton();
        Jbsalvar = new javax.swing.JButton();
        Jbsair = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");

        Jtnome.setEnabled(false);
        Jtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtnomeActionPerformed(evt);
            }
        });

        Jtend.setEnabled(false);
        Jtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtendActionPerformed(evt);
            }
        });

        Jtcpf.setEnabled(false);

        jbnovo.setText("Novo");
        jbnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovoActionPerformed(evt);
            }
        });

        jbexcluir.setText("Excluir");
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");

        jLabel3.setText("CPF");

        Jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Endereço", "Cpf", "Rg", "Renda", "Senha", "email"
            }
        ));
        jScrollPane2.setViewportView(Jtb1);

        Jtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtcodActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo");

        jLabel7.setText("RG");

        Jtrg.setEnabled(false);
        Jtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtrgActionPerformed(evt);
            }
        });

        jLabel8.setText("Renda");

        jLabel9.setText("Senha");

        Jtrenda.setEnabled(false);

        Jtsenha.setEnabled(false);
        Jtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtsenhaActionPerformed(evt);
            }
        });

        jLabel10.setText("Email");

        Jtemail.setEnabled(false);

        Jbeditar.setText("Editar");
        Jbeditar.setEnabled(false);
        Jbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbeditarActionPerformed(evt);
            }
        });

        Jbsalvar.setText("Salvar");
        Jbsalvar.setEnabled(false);
        Jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsalvarActionPerformed(evt);
            }
        });

        Jbsair.setText("Sair");

        jbcancelar.setText("Cancelar");
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jbeditar)
                        .addGap(18, 18, 18)
                        .addComponent(Jbsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(Jbsair)
                        .addGap(18, 18, 18)
                        .addComponent(jbexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbcancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(Jtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Jtend, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(Jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Jtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnovo)
                    .addComponent(Jbeditar)
                    .addComponent(Jbsalvar)
                    .addComponent(Jbsair)
                    .addComponent(jbexcluir)
                    .addComponent(jbcancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        setBounds(0, 0, 560, 548);
    }// </editor-fold>//GEN-END:initComponents

    private void JtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtnomeActionPerformed

    private void JtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtendActionPerformed

    private void JtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtsenhaActionPerformed

    private void JtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtcodActionPerformed

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcancelarActionPerformed

    private void JbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsalvarActionPerformed
        String cod=Jtcod.getText().trim();
        String nome=Jtnome.getText().trim();
        String endereço=Jtend.getText().trim();
        String cpf=Jtcpf.getText().trim();
        String rg=Jtrg.getText().trim();
        String renda=Jtrenda.getText().trim();
        String senha=Jtsenha.getText().trim();
        String email=Jtemail.getText().trim();
        
        DefaultTableModel val = (DefaultTableModel)Jtb1.getModel();
        
        val.addRow(new String[]{cod,nome,endereço,cpf,rg,renda,senha,email});
        
               
       
        
        
        
        Jtcod.setText("");
        Jtnome.setText("");
        Jtend.setText("");
        Jtcpf.setText("");
        Jtrg.setText("");
        Jtrenda.setText("");
        Jtsenha.setText("");
        Jtemail.setText("");
       
        Jtnome.requestFocus();  
      
         
     
       
       
    }//GEN-LAST:event_JbsalvarActionPerformed

    private void JbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbeditarActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_JbeditarActionPerformed

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed

    }//GEN-LAST:event_jbexcluirActionPerformed

    private void jbnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovoActionPerformed
        Jtnome.setEnabled(true);
        Jtend.setEnabled(true);
        Jtcpf.setEnabled(true);
        Jtrg.setEnabled(true);
        Jtrenda.setEnabled(true);
        Jtsenha.setEnabled(true);
        Jtemail.setEnabled(true);
        
        Jbeditar.setEnabled(true);
        Jbsalvar.setEnabled(true);
        jbcancelar.setEnabled(true);
        
    }//GEN-LAST:event_jbnovoActionPerformed

    private void JtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbeditar;
    private javax.swing.JButton Jbsair;
    private javax.swing.JButton Jbsalvar;
    private javax.swing.JTable Jtb1;
    private javax.swing.JTextField Jtcod;
    private javax.swing.JTextField Jtcpf;
    private javax.swing.JTextField Jtemail;
    private javax.swing.JTextField Jtend;
    private javax.swing.JTextField Jtnome;
    private javax.swing.JTextField Jtrenda;
    private javax.swing.JTextField Jtrg;
    private javax.swing.JTextField Jtsenha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jbnovo;
    // End of variables declaration//GEN-END:variables

}


        
    
  
         
   
    







